import json
import time
from typing import Dict, Any, Set

class ExcessiveAgencyInterceptor:
    def __init__(self):
        # Destructive or high-privilege actions that REQUIRE explicitly elevated user status
        self.restricted_actions: Set[str] = {
            "delete_account",
            "modify_billing",
            "flush_database",
            "grant_admin_privileges"
        }

    def intercept_agent_call(self, agent_payload_json: str, user_role: str) -> Dict[str, Any]:
        """
        Intercepts and evaluates automated agent execution choices against runtime user permissions.
        """
        start_time = time.perf_counter()
        normalized_role = user_role.lower().strip()

        try:
            # Parse the tool instruction generated by the model
            payload = json.loads(agent_payload_json)
            requested_action = payload.get("action")
            
            # Step 1: Detect if the model is attempting a restricted system command
            if requested_action in self.restricted_actions:
                # Step 2: Privilege Boundary Verification
                if normalized_role != "admin":
                    execution_time = time.perf_counter() - start_time
                    return {
                        "verdict": "REJECTED",
                        "reason": f"OWASP-LLM06: Privilege Escalation Blocked. Agent attempted action '{requested_action}' but user role '{user_role}' lacks authority.",
                        "overhead_seconds": f"{execution_time:.7f}"
                    }

        except (json.JSONDecodeError, TypeError, ValueError):
            execution_time = time.perf_counter() - start_time
            return {
                "verdict": "REJECTED",
                "reason": "Malformed agent instruction schema payload.",
                "overhead_seconds": f"{execution_time:.7f}"
            }

        execution_time = time.perf_counter() - start_time
        return {
            "verdict": "🟢 Passed",
            "action_approved": requested_action,
            "overhead_seconds": f"{execution_time:.7f}"
        }

if __name__ == "__main__":
    print("🛡️ Initializing Phase 2: Day 31 OWASP LLM06 Excessive Agency Interceptor...")
    interceptor = ExcessiveAgencyInterceptor()
    
    # Simulation: A regular customer tricks the LLM agent into triggering an account deletion routine
    hijacked_agent_payload = """
    {
        "action": "delete_account",
        "parameters": {
            "target_user_id": "usr_99201"
        }
    }
    """
    
    # Run audit passing a non-admin role
    result = interceptor.intercept_agent_call(hijacked_agent_payload, user_role="customer")
    print(f"\n📊 Runtime Interceptor Diagnostic Evaluation Result:")
    print(json.dumps(result, indent=2, ensure_ascii=False))